sudo: required
matrix:
  include:
    - language: java
      jdk: openjdk8

      before_install:
        - sudo apt-get update -qq

      script:
        - cd ./ida-ws      
        - mvn clean install -DskipTests -P linux
        - mvn test 

      cache:
        directories:
          - $HOME/.m2
#    - language: node_js
#      node_js: "10"
#      script:
#        - cd ./ida-chatbot
#        - npm ci
#        - npm run test-headless
        
      after_success:
       - mvn cobertura:cobertura
       - export CODECOV_TOKEN="a147793a-a3ba-43f1-8192-261537314090"
       - bash <(curl -s https://codecov.io/bash)
  

